export const employees = [
  "Andy Simone",
  "Cory Berry",
  "Darcy Hogg",
  "David Berry",
  "David Looney",
  "Evan Berry",
  "Igor Lalic",
  "Jeff Kainec",
  "Jim Wargo",
  "Josh Berry",
  "Lorraina Smith",
  "Marilyn Berry",
  "Nate Kainec",
  "Nick Babic",
  "Sam Santabarbara",
  "Tony Risko",
  "Tyler Smith",
  "Cheyenne Falz",
  "Carole Vorisek",
  "Patty Russo",
  "Ryan Thomas",
  "Stephen Sanders",
  "Michael Vanderwyst",
  "Patrick Jovanovic",
  "Alex Trivonovich"
];
