export const apecVendors =  ["1000Bulbs",
  "11x17",
  "16246Allied Electronics & Automation",
  "7West Design",
  "80/20",
  "A. DePaulo Trucking",
  "Abel Metal Processing Inc",
  "ACS Group",
  "Acuity Insurance",
  "Adcon Engineering",
  "Admiral Metals",
  "Adobe Inc",
  "Advanced Innovative Manufacturing, Inc.",
  "Ahola Payroll Services",
  "AirControl Products",
  "Airgas",
  "Aitken MFG",
  "Akron Belting and Supply",
  "Alabaster",
  "All Lift Service Inc",
  "Allen Graphics",
  "Allfasteners",
  "AllFuses.com",
  "Allied Wire and Cable",
  "Alloy Products",
  "Alro Steel",
  "AluminumSpacers.com",
  "Amazon Capital Services",
  "Amazon Marketplace",
  "Amazon Prime",
  "American Abatement & Asbestos Removal",
  "Andrew Simone",
  "Andrews Industrial Controls, Inc.",
  "Anixter",
  "Anodizing Specialists",
  "Anthem Blue Cross Blue Shield",
  "Anthem Dental",
  "APEC Engineering Inc",
  "APEC Holdings, LLC",
  "Apec Thermal, Div of APEC",
  "Apex Welding, Inc. dba Apex Bulk Handlers",
  "Arc Document Solutions, LLC",
  "Arclight Dynamics",
  "Artisan Technology Group",
  "ASO Safety Solutions",
  "Auto",
  "AutoDesk",
  "Automated Systems Engineering Inc",
  "Automation Direct",
  "Automation4Less",
  "AVA Direct",
  "Avery Products",
  "Avondale Wholesale Parts",
  "Baker's Gas & Welding Supplies, Inc",
  "Barker Controls",
  "Barrington Carpet and Flooring Design",
  "Bay Fastening Systems",
  "Beacon Gasket & Seals Co",
  "Beatrice Uljanic",
  "Bedford City Schools Foundation",
  "Bedford Downtown Alliance",
  "Bedford Lions Club",
  "Ben L. Jonozzo, CPA, Inc.",
  "Bentley Mills, Inc.",
  "Berrington Pumps & Systems, Inc.",
  "Berry, David",
  "Berry, Evan",
  "Berry, Marilyn",
  "Bican Home Improvement Company, Inc.",
  "Bican Plumbing, Inc.",
  "Blind Rivet Supply",
  "BLJ Adjust",
  "Bodin-Electric",
  "Boroski Auto Body",
  "BradyID",
  "Brake Products Inc",
  "Brian Berry",
  "Bruder Building Materials",
  "Buckeye Lubricants Inc",
  "Buckeye Pumps Inc",
  "Buckeye Scale",
  "Burton Middlefield Rotary",
  "Cable Ties and More",
  "Car Rental",
  "Carbonite",
  "Carlos Johnson",
  "Carr Bros., Inc.",
  "Carter Lumber",
  "CEICO Inc",
  "Checks Unlimited",
  "ChemWorld",
  "Cheyenne Falz.",
  "Chocolate Bliss By Kim",
  "Chris Holley",
  "Cincinnati Fan",
  "Cincinnati Inc.",
  "Citizens Bank",
  "Citizens Bank Credit Card",
  "City Electric Supply",
  "City of Bedford - Tax Department",
  "City of Bedford.",
"Classic Automation",
"Clausing Industrial",
"Cleveland Concrete Coatings",
"Cleveland Punch & Die",
"Cleveland Vicon",
"Clint Meadows",
"CNC Associates, Inc.",
"Cole-Parmer",
"Colony Hardware Corp",
"Comfort Systems USA",
"CompManagement Health Systems...CareWorks",
"Computer Aided Technology",
"Concentra",
"Control Devices",
"Controlco Inc",
"Conveyor & Caster",
"CPE Solutions",
"CR-TEC Engingeering",
"CR Magnetics",
"CRB Carbonite Backup",
"Crescent Electric",
"Cross",
"CSP Construction, Inc.",
"CTAM",
"Cumberland",
"Custom Clutch Joint & Hydraulics, Inc",
"Cuyahoga County Treasurer",
"CVS Bedford",
"Darcy Hogg.",
"David C. Berry",
"David Industrial Sales, LLC",
"David Looney, Sr.",
"DBS Communications",
"deluxe",
"Depreciation Expense",
"Digi-Key Electronics",
"Distillata",
"Divvy",
"Dominion Energy",
"Door Works & Construction",
"Drive Source International",
"DropBox",
"Dungs Combustion Controls",
"Dwyer Instruments",
"DXP Enterprises",
"E-Z Pass",
"E.S. Sign & Design",
"Eastern Tool Company",
"Easy Lift Equipment",
"eBay",
"ElecDirect.com",
"Electro-Chemical Devices",
"Electro-Matic Products",
"Elicense Transaction Fee",
"emedco",
"EMG USA, Inc.",
"EMKA",
"Energy Avenue",
"Eng&SurveyBD",
"Equipment Sales and Service",
"Essentra Components",
"EST Insulation, LLC",
"Ethan Byrnes",
"Everlast",
"Exit Sign Warehouse",
"ExitLightCo.com ",
"Fabins Trailers & Truck",
"Fallsway Equipment Company",
"Fantastic Embroidery and Screen Printing",
"FASTech, Inc.",
"Fastenal",
"Federal Signal",
"FedEx",
"FES",
"Fluidtrols",
"FMS USA Inc",
"Formica Plumbing & Sewer Co.",
"Franklin Templeton Investments",
"Franklyn W Kirk Co",
"Freightquote.com",
"Fronius USA LLC",
"FS Industries",
"Galco",
"Gamble, Jehrie",
"Gas Station",
"General Insulation Company",
"General Store",
"Getter Control Systems",
"Global Industrial",
"Global LED Solutions",
"GOOGLE",
"GOOGLE Ads",
"Google Pandora",
"Gordon Electric Suppply Inc.",
"GotPrint.com",
"Grainger",
"Graybar",
"Graybar Electric Company",
"GRG Trucking Co. Inc",
"Gust & Adolf's Auto Parts",
"Haas Tooling",
"Hamilton Parker Company",
"Hansen Supply",
"HAR Adhesives",
"HAR Equipment Sales",
"Harbor Freight",
"Harrington Electric",
"Harrington Industrial Plastics",
"Heatmax",
"Hewlitt Packard",
"HFO Midwest (Midwest Manuf. Resources)",
"HGR Industrial",
"HMS Network",
"Hoist & Crane Service Group",
"Home Depot",
"Home Depot Credit Card",
"Horner Heating & Air",
"Hotel",
"I Am Your Guy LLC",
"I Squared R Element Co Inc",
"IFM",
"Igor Lalic",
"Illuminating Company",
"Imaginit Technologies/Rand",
"Imgident",
"Indeed",
"Indiana Professional Licensing Agency",
"Industrial Fans Direct",
"Industrial Gas Spring",
"inkTech",
"Instrumart",
"Ioppolo Concrete Corp.",
"IPLA",
"JACS Home Improvement",
"James Wargo.",
"Jeffrey Kainec",
"JJB Engineering, Inc.",
"JME Sales",
"Joe Bican",
"John Hancock",
"Jonathon Nicolazzo",
"Jones Machinery, Inc",
"Jose Cruz",
"Joshua Darty-Berry",
"JRC Web Accessories, Inc",
"K&J Magnetics",
"Kapton Caulking and Building Restoration",
"Karl Dungs Inc",
"Katherine Babic",
"KDK Reps",
"Keene Building Products",
"Ken Ganley of Bedford",
"Kennametal",
"Kent Industries",
"Keyence",
"Koltcz Concrete Block",
"Kurt J. Lesker Company",
"Kurt Kainec",
"L & M Tool and Industrial Supply Inc",
"Labor Law Compliance Center",
"Lake Erie Golf Carts",
"Lakeland Glass Company, Inc.",
"Lakewood Automation",
"Lambda Laboratory Instruments",
"LampTech",
"last pass",
"Lattner",
"Lawson Products",
"Lectro Components",
"Legend Tube",
"Linemaster",
"Lorraina Syacsure",
"Lowe's",
"Lugs Direct",
"Lyndall Associates, Inc",
"Maddox Industrial Transmission",
"Mars Electric Co.",
"Marsam Metalfab, Inc.",
"Marshall Wolf Automation",
"Mate Precision Technologies",
"Matthew Sabo",
"Max and Associates",
"Maxcess Americas dba Fife frmly Componex",
"Maxon, A Honeywell Company",
"McCarthy, Lebit, Crystal & Liffman Co.,",
"McMaster-Carr",
"McNichols Co.",
"Meier Transmission",
"Menards",
"MES Mechanical Electrical Systems",
"Metal Deck Direct",
"Metal Supermarkets",
"Metals Depot International",
"MetroPCS",
"Micro Center",
"Microsoft",
"Mixer Direct",
"Mono-Price",
"Motion AI",
"Motion Industries Inc",
"Motion Technologies Co.",
"Mouser Electronics, Inc.",
"Mr T Painting Company, Inc.",
"MSC Industrial Supply Co.",
"Multi Service TE",
"Munters Corporation",
"My Safety Labels",
"Napa Auto Parts",
"Nate Kainec",
"National Car Rental",
"National Pen",
"Naugatuck Mfg Company, Inc",
"NEFD",
"Neff Group Distributors, Inc.",
"Networks",
"Newark Usa",
"Newegg",
"newegg.com",
"Nick Babic",
"Nordonia Hills Chamber of Commerce",
"North Machine Tool",
"Northeast Ohio Supply",
"Northern Tools",
"Northfield Tire",
"NRI Industrial",
"O'Reilly Auto Parts",
"Oakwood Village Hardware",
"ODJFS - Ohio Dept. Job & Fam. Services",
"Officemax",
"Ohio BWC",
"Ohio CAT - The CAT Rental Store",
"Ohio Chamber of Commerce",
"Ohio Dept. of Taxation - CAT Tax",
"Ohio Pipe, Valve & Fittings, Inc.",
"Omega Engineering",
"ONEX",
"ONEX Inc",
"Online Components",
"Optima Scale",
"Orientalmotors",
"Osborne, Inc. - Mentor",
"OTP Industrial Solutions",
"Panitoid",
"Parking",
"PartsMaster Division of Lawson Products",
"Patty Russo",
"PayChex",
"PC Industrial Controls",
"PCM Thermal Solutions Inc.",
"Pepco",
"Pepperl+Fuchs, Inc",
"Perri Volz",
"Pete & Pete Container Service, Inc.",
"Plastic Process Equipment",
"Plotterpaperdirect.com",
"Plumbing Deals",
"Porter Metal Company",
"Powertech Controls",
"Precision Devices",
"Progressive Insurance",
"Pucel",
"pvcfittingsonline.com",
"PY Factur",
"Quadrel",
"Quality IP",
"Quill Corporation",
"Radwell Internatiional",
"RapidAir",
"Raven Technological Servcies",
"Raytek-Direct",
"Regional Income Tax Agency",
"Republic Services",
"Restaurant",
"Rexel",
"Reza Hashemi.",
"Rich DeCaria",
"Rick Gaug",
"RiverCor.",
"Rivets",
"RLI",
"Robeck Fluid Power Co.",
"Robert-James Sales, Inc.",
"Rol-Fab",
"Roll-2-Roll Technologies",
"RS America",
"Ryan Rosenfeld.",
"Ryan Thomas",
"S.W. Anderson Co",
"Safety Label Solutions",
"Saginaw Control",
"SalesForce.Com",
"Sam's Club",
"Sams Club",
"Samsel Supply",
"Samuel Santabarbara",
"Sanders, Stephen",
"Sanitary Fittings, LLC",
"SC Fastening Systems",
"SC Industrial Sales",
"Scam Charge",
"Seasons Roofing, Inc.",
"Sedgwick",
"Service Caster Corporation",
"Shaltz Automation, Inc.",
"Sherwin Williams",
"Shop Welding Supplies",
"Silco Fire & Security",
"Sixmo, Inc.",
"Smartsign",
"SMC Pneumatics",
"SME",
"Smoky Mountain Emporium, Inc",
"SOCA - Southern Ohio Chamber Alliance",
"Southgate Lock and Security",
"SP Octane",
"Spectrum - Cable/Phone",
"Spectrum, Inc.",
"Spee-D Metals",
"Stan Koci",
"Standard Electric Supply",
"Stark County Building Department",
"State Motor and Control Solutions",
"Stud Welding Products Inc",
"Summers Rubber",
"Sunbelt Rentals",
"Super Breakers",
"SupplyHouse.com",
"Sutton Industrial Hardware",
"Swagelok Cleveland",
"Szabo, Chuck",
"T-Mobile",
"Tank-Depot.com",
"Tank and Barrel",
"TASC",
"TC Measurement and Control, Inc.",
"TCDirect",
"Team Air Express",
"TechSouth Inc",
"Terrill Technical Consulting Group",
"TForce Freight",
"The City Mission",
"The Envelope Printery of Ohio",
"The Lindner Law Firm LCC",
"The Lindner Law Firm LLC",
"The MOD Pros.",
"The Motor Control Center",
"The Ohio Treasurer of State",
"The Retirement Advantage, Inc.",
"The Tim Cruz Foundation",
"Thomson Linear",
"Thors ELearning Solutions",
"Titans of CNC",
"Toledo Metal Spinning Comp",
"Tony Risko",
"Total Industrial Mainentance Services",
"Traffic Control Products",
"Transfer",
"Travel",
"Treasurer State of Ohio-ENG",
"Treasurer State of West Virginia",
"Treasurer, State of Ohio",
"Tri-State Valve",
"Trivonovich, Alex",
"Turk & Hillinger",
"Twinco MFG",
"Tyler Smith",
"Ubiquiti",
"ULINE",
"Ullman Electric",
"United Rentals",
"United States Plastic Corp.",
"United States Treasury",
"Universal Printing Solutions",
"UPS",
"UPS Freight",
"US Bank Credit Card - APEC Holdings",
"US Bank Loan",
"USA Lab",
"USF Holland, LLC",
"USPS",
"Valworx",
"Vanderwyst, Michael",
"Vega",
"Verizon Wireless",
"Virginia Tile Company",
"Vorne",
"W.E.S.T. Forwarding Services",
"W.H. Kay Company",
"Wagner Companies",
"WalMart.com",
"Warehouse Rack and Shelf",
"Wayfair",
"Webroot Inc.",
"Webstaurant Store.com",
"Wesco",
"Western Engravers Supply, Inc.",
"Wikipedia",
"Williams Automation",
"wisco",
"Woodhill Supply",
"WorldPay",
"WVIZ/PBS Ideastream",
"Yarde Metals",
"ZORO",
  ]
